#!/bin/python3
import os
import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    # Parse t1 string into a datetime object using strptime with format: 
    # day of the week, day of the month, abbreviated month, year, time (HH:MM:SS), and timezone.
    t1 = datetime.datetime.strptime(t1,'%a %d %b %Y %H:%M:%S %z')
    
    # Parse t2 string into a datetime object using the same format as t1.
    t2 = datetime.datetime.strptime(t2,'%a %d %b %Y %H:%M:%S %z')
    
    # Calculate the absolute difference between t1 and t2, 
    # then get the total difference in seconds using total_seconds().
    # Round the result to the nearest whole number and convert it to a string.
    return str(abs(round((t1 - t2).total_seconds())))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
